config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  devise_for :users

  authenticate do
    namespace :users, path: :my do
      resources :bounties
    end
  end

  resources :bounties

  get "/how-it-works", to: "static#how_it_works"

  get 'filters', to: 'bounties#filters'
  get 'open_filter', to: 'bounties#open_filter'
  get 'assigned_filter', to: 'bounties#assigned_filter'
  get 'completed_filter', to: 'bounties#completed_filter'

  # Defines the root path route ("/")
  root "bounties#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bounty.rb
class Bounty < ApplicationRecord
  STATUSES = %w[open assigned complete]

  belongs_to :user
  has_rich_text :description

  scope :sorted, -> { in_order_of(:status, STATUSES).order(created_at: :desc) }
  scope :filtered, ->(status) { where(status: status) }

  validates :amount, presence: true, numericality: {greater_than: 0, only_integer: true}
  validates :description, presence: true
  validates :status, inclusion: {in: STATUSES}
  validates :title, presence: true
  validates :url, presence: true, format: {with: /\Ahttps?:\/\//}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_person_name

  has_many :bounties, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  include Pagy::Backend

  before_action :set_bounty, only: %i[show]

  # GET /bounties or /bounties.json
  def index
    params[:filter] = "open" if params[:filter].nil?
    @bounties = Bounty.sorted
    @filter, @bounties = params[:filter], @bounties.filtered(params[:filter]) if Bounty::STATUSES.include?(params[:filter])
    @pagy, @bounties = pagy(@bounties)
  end

  # GET /bounties/1 or /bounties/1.json
  def show
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bounty
    @bounty = Bounty.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def how_it_works
  end
end

app/controllers/users/bounties_controller.rb
class Users::BountiesController < ApplicationController
  include Pagy::Backend

  before_action :set_bounty, only: %i[show edit update destroy]

  # GET /bounties
  def index
    @pagy, @bounties = pagy(current_user.bounties.sorted)
  end

  # GET /bounties/1
  def show
  end

  # GET /bounties/new
  def new
    @bounty = Bounty.new
  end

  # GET /bounties/1/edit
  def edit
  end

  # POST /bounties
  def create
    @bounty = current_user.bounties.new(bounty_params)

    if @bounty.save
      redirect_to users_bounty_url(@bounty), notice: "Bounty was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /bounties/1
  def update
    if @bounty.update(bounty_params)
      redirect_to users_bounty_url(@bounty), notice: "Bounty was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /bounties/1
  def destroy
    @bounty.destroy
    redirect_to users_bounties_url, notice: "Bounty was successfully destroyed."
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_bounty
    @bounty = current_user.bounties.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def bounty_params
    params.require(:bounty).permit(:title, :description, :url, :amount, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def nav_link_to(name = nil, options = {}, html_options = {}, &block)
    if block
      html_options = options
      options = name
      name = block
    end

    url = url_for(options)
    starts_with = html_options.delete(:starts_with)
    html_options[:class] = Array.wrap(html_options[:class])
    active_class = html_options.delete(:active_class) || "active"
    inactive_class = html_options.delete(:inactive_class) || ""

    active = if (paths = Array.wrap(starts_with)) && paths.present?
      paths.any? { |path| request.path.start_with?(path) }
    else
      request.path == url
    end

    classes = active ? active_class : inactive_class
    html_options[:class] << classes unless classes.empty?

    html_options.except!(:class) if html_options[:class].empty?

    return link_to url, html_options, &block if block

    link_to name, url, html_options
  end
end

app/helpers/bounties_helper.rb
module BountiesHelper
  def status_badge(status)
    color = case status
    when "open"
      "text-green-800 bg-green-100"
    when "assigned"
      "text-blue-800 bg-blue-100"
    else
      "text-indigo-800 bg-indigo-100"
    end

    tag.div status.humanize, class: "#{color} inline-flex items-center rounded-full px-2.5 py-0.5 text-sm font-semibold"
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/bounties/_bounty.html.erb
<div id="<%= dom_id bounty %>" class="mb-8 bg-white border shadow rounded-md pt-8 px-8">
  <div class="flex justify-between gap-8">
    <h2 class="m-0"><%= link_to bounty.title, bounty_path(bounty), class: "no-underline font-bold tracking-tight" %></h2>

    <div class="mb-4 text-2xl font-bold text-green-600">
      <%= number_to_currency bounty.amount, precision: 0 %>
    </div>
  </div>

  <%= simple_format truncate(bounty.description.to_plain_text, length: 1000) %>

  <div class="bg-gray-50 -mx-8 px-8 py-4">
    <div class="flex items-center justify-between gap-8">
      <%= status_badge bounty.status %>

      <div class="flex items-center gap-4">
        <div class="text-sm">Created by <%= bounty.user.name %></div>
        <%= link_to bounty.url, class: "no-underline inline-flex gap-2 items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500", target: :_blank do %>
          View Project
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline w-5 h-5">
            <path fill-rule="evenodd" d="M4.25 5.5a.75.75 0 00-.75.75v8.5c0 .414.336.75.75.75h8.5a.75.75 0 00.75-.75v-4a.75.75 0 011.5 0v4A2.25 2.25 0 0112.75 17h-8.5A2.25 2.25 0 012 14.75v-8.5A2.25 2.25 0 014.25 4h5a.75.75 0 010 1.5h-5z" clip-rule="evenodd" />
            <path fill-rule="evenodd" d="M6.194 12.753a.75.75 0 001.06.053L16.5 4.44v2.81a.75.75 0 001.5 0v-4.5a.75.75 0 00-.75-.75h-4.5a.75.75 0 000 1.5h2.553l-9.056 8.194a.75.75 0 00-.053 1.06z" clip-rule="evenodd" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bounties/_hero.html.erb
<div class="mx-auto max-w-7xl py-4">
  <div class="relative isolate overflow-hidden bg-gray-900 px-6 py-8 text-center shadow-2xl sm:rounded-3xl sm:px-16">
    <h2 class="my-4 mx-auto max-w-2xl text-3xl font-bold tracking-tight text-white sm:text-4xl">Small projects for Junior Developers</h2>
    <p class="mx-auto mt-4 max-w-xl text-lg leading-8 text-gray-300">Help Junior developers get hired by sharing small projects they can work on to build their resume with paid work.</p>
    <div class="mt-4 flex items-center justify-center gap-x-6">
      <%= link_to "Post a bounty", new_user_registration_path, class: "no-underline rounded-md bg-white px-3.5 py-2.5 text-sm font-semibold text-gray-900 shadow-sm hover:bg-gray-100 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white" %>
      <a href="<%= how_it_works_path %>" class="text-sm font-semibold leading-6 text-white">How it works <span aria-hidden="true">→</span></a>
    </div>
    <svg viewBox="0 0 1024 1024" class="absolute top-1/2 left-1/2 -z-10 h-[64rem] w-[64rem] -translate-x-1/2 [mask-image:radial-gradient(closest-side,white,transparent)]" aria-hidden="true">
      <circle cx="512" cy="512" r="512" fill="url(#827591b1-ce8c-4110-b064-7cb85a0b1217)" fill-opacity="0.7" />
      <defs>
        <radialGradient id="827591b1-ce8c-4110-b064-7cb85a0b1217">
          <stop stop-color="#7775D6" />
          <stop offset="1" stop-color="#E935C1" />
        </radialGradient>
      </defs>
    </svg>
  </div>
</div>

app/views/bounties/assigned_filter.html.erb
<% unless user_signed_in? %>
  <%= render 'hero' %>
<% end %>

<%= turbo_frame_tag "current_filter" do %>
  <h2>Assigned Bounties</h2>
  <%= render 'shared/bounties_filter' %>

  <%= render Bounty.where(status: "assigned") %>

<% end %>

app/views/bounties/completed_filter.html.erb
<% unless user_signed_in? %>
  <%= render 'hero' %>
<% end %>

<%= turbo_frame_tag "current_filter" do %>
  <h2>Completed Bounties</h2>
  <%= render 'shared/bounties_filter' %>

  <%= render Bounty.where(status: "complete") %>

<% end %>

app/views/bounties/filters.html.erb
<%= turbo_frame_tag "filters" do %>
  <%= turbo_frame_tag "current_filter", src: bounties_path %>
<% end %>

app/views/bounties/index.html.erb
<%= render "hero" unless user_signed_in? %>

<div class="my-8 flex gap-2 items-center justify-between">
  <h2 class="m-0"><%= (@filter || "All").titleize %> Bounties</h2>
  <nav class="flex gap-2">
    <%= link_to "All", bounties_path(filter: "none"), class: class_names("font-bold" => @filter.blank?) %>
    <% Bounty::STATUSES.each do |status| %>
      <%= link_to status.titleize, bounties_path(filter: status), class: class_names("font-bold" => status == @filter) %>
    <% end %>
  </nav>
</div>

<% if @bounties.present? %>
  <div id="bounties">
    <%= render @bounties %>
  </div>

  <%== pagy_nav(@pagy).html_safe %>
<% else %>
  <% if @filter == "open" %>
    <p class="m-8 md:m-12 text-center italic text-lg md:text-xl">
      There are no open bounties right now.
      <br>
      Spread the word that we need people to post new Beginner Bounties!
    </p>
  <% end %>
<% end %>

app/views/bounties/open_filter.html.erb
<% unless user_signed_in? %>
  <%= render 'hero' %>
<% end %>

<%= turbo_frame_tag "current_filter" do %>
  <h2>Open Bounties</h2>
  <%= render 'shared/bounties_filter' %>
  <%= render Bounty.where(status: "open") %>
<% end %>

app/views/bounties/show.html.erb
<div class="space-y-4">
  <%= link_to '← Back to bounties', bounties_path, class: "no-underline" %>
  <%= render @bounty %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full">
  <head>
    <title>
      <%= content_for?(:title) ? "#{yield(:title)} | Beginner Bounties" : "Beginner Bounties" %>
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <meta property="og:title" content="Beginner Bounties" />
    <meta property="og:type" content="website" />
    <meta property="og:description" content="Help Junior developers get hired by sharing small projects they can work on to build their resume with paid work." />
    <meta property="og:url" content="<%= root_url %>" />
    <meta property="og:image" content="<%= image_url("open_graph.png") %>" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Beginner Bounties" />
    <meta name="twitter:description" content="Help Junior developers get hired by sharing small projects they can work on to build their resume with paid work." />
    <meta name="twitter:url" content="<%= root_url %>" />
    <meta name="twitter:image" content="<%= image_url("open_graph.png") %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body class="flex flex-col h-screen justify-between">
    <main>
      <%= render "shared/navbar" %>
      <%= render "shared/flash" %>

      <div class="max-w-7xl mx-auto p-6 lg:px-8 prose">
        <%= yield %>
      </div>

    </main>
    <footer>
      <%= render "shared/footer" %>
    </footer>
  </body>
</html>

app/views/shared/_bounties_filter.html.erb
<div class="flex mb-4">
  <nav>
    <%= filter_link_to "all", bounties_path,
      active_class: "border-indigo-500 text-indigo-600",
      class: "border-b-2 text-sm font-medium no-underline" %>
    <%= filter_link_to "open", open_filter_path,
      active_class: "border-indigo-500",
      class: "border-b-2 text-sm font-medium no-underline" %>
    <%= filter_link_to "assigned", assigned_filter_path,
      active_class: "border-indigo-500",
      class: "border-b-2 text-sm font-medium no-underline" %>
    <%= filter_link_to "completed", completed_filter_path,
      active_class: "border-indigo-500",
      class: "border-b-2 text-sm font-medium no-underline" %>
  </nav>
</div>

app/views/shared/_flash.html.erb
<% if notice.present? %>
  <div class="my-4 max-w-7xl mx-auto py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg" id="notice"><%= notice %></div>
<% end %>

<% if alert.present? %>
  <div class="my-4 max-w-7xl mx-auto py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg" id="alert"><%= alert %></div>
<% end %>

app/views/shared/_footer.html.erb
<div class="w-full h-auto px-2 py-4 text-sm lg:px-6 max-w-7xl mx-auto">
  <div class="flex p-4 text-sm flex-row justify-between">
    <div class="flex items-center justify-center">
      <div class="text-gray-700">© <%= Date.current.year %> <%= link_to "GoRails", "https://gorails.com/", target: "_blank" %></div>
    </div>

    <div class="flex flex-wrap justify-center items-center">
      <%= link_to "How it works", how_it_works_path, class: "text-gray-700 no-underline block px-4" %>
      <a href="https://github.com/excid3/beginnerbounties.com" target="_blank" class="text-gray-400 hover:text-gray-500">
        <span class="sr-only">GitHub</span>
        <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
        </svg>
      </a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="bg-gray-900 text-white shadow-lg">
  <nav class="mx-auto flex max-w-7xl items-center justify-between gap-x-6 p-6 lg:px-8" aria-label="Global">
    <%= link_to root_path do %>
      <h1 class="hidden md:block font-bold md:text-2xl m-0 uppercase">
        Beginner<span class="ml-1 p-0.5 bg-white text-gray-900">Bounties</span>
      </h1>

      <h1 class="md:hidden font-bold md:text-2xl m-0 uppercase">
        B<span class="ml-1 p-0.5 bg-white text-gray-900">B</span>
      </h1>
    <% end %>

    <div class="text-sm md:text-base flex lg:gap-x-12">
      <%= nav_link_to "Bounties", bounties_path, class: "text-white text-sm font-semibold leading-6", active_class: "border-b-2 border-indigo-500 px-2.5 -mx-2.5" %>
    </div>
    <div class="flex flex-1 items-center justify-end gap-x-6">
      <%= nav_link_to "Post a bounty", new_users_bounty_path, class: "rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      <% if user_signed_in? %>
        <%= nav_link_to "My Bounties", users_bounties_path, class: "text-white text-sm font-semibold leading-6", active_class: "border-b-2 border-indigo-500 px-2.5 -mx-2.5" %>
        <%= link_to "Profile", edit_user_registration_path, class: "text-white text-sm font-semibold leading-6" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "text-white text-sm font-semibold leading-6" %>
      <% else %>
        <%= link_to "Log in", new_user_session_path, class: "text-white text-sm font-semibold leading-6" %>
        <%#= link_to "Sign Up", new_user_registration_path, class: "rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
      <% end %>
    </div>
  </nav>
</header>

app/views/users/bounties/_bounty.html.erb
<div id="<%= dom_id bounty %>" class="bg-white mb-8 border shadow rounded-md pt-8 px-8">
  <div class="flex justify-between">
    <div class="mb-4 text-2xl font-bold text-green-600">
      <%= number_to_currency bounty.amount, precision: 0 %>
    </div>

    <%= link_to 'Edit this bounty', edit_users_bounty_path(bounty), class: "text-blue-500 no-underline hover:underline" %>
  </div>

  <div class="[overflow-wrap:anywhere]">
    <h2 class="m-0 break-words"><%= bounty.title %></h2>
    <div class="text-sm">Created by <%= bounty.user.name %></div>
    <%= simple_format truncate(bounty.description.to_plain_text, length: 1000) %>
  </div>

  <div class="bg-gray-50 -mx-8 px-8 py-4">
    <div class="flex items-center justify-between gap-8">
      <%= form_for bounty, url: users_bounty_path(bounty), method: :patch do |f| %>
        <%= f.select :status, Bounty::STATUSES.map{|s| [s.humanize, s] }, {}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mr-5 mt-2 w-full", onchange: "this.form.submit()"} %>
      <% end %>

      <%= link_to bounty.url, class: "no-underline flex items-center gap-1", target: :_blank do %>
        View Project
        <svg class="inline h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>
  </div>
</div>

app/views/users/bounties/_form.html.erb
<%= form_with(model: [:users, bounty], class: "contents") do |form| %>
  <% if bounty.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(bounty.errors.count, "error") %> prohibited this bounty from being saved:</h2>

      <ul>
        <% bounty.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, required: true, placeholder: "Help with a feature on my open source project", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.rich_text_area :description, required: true, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :url %>
    <%= form.url_field :url, required: true, placeholder: "https://github.com/username/myrepo/issues/1", class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.number_field :amount, required: true, placeholder: 25, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <% if form.object.persisted? %>
    <div class="my-5">
      <%= form.label :status %>
      <%= form.select :status, Bounty::STATUSES.map{|s| [s.humanize, s] }, {}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"} %>
    </div>
  <% end %>

  <div class="flex">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
    <% if form.object.persisted? %>
      <%= link_to "Cancel", users_bounty_path(form.object), class: "no-underline ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="flex w-full justify-end">
        <%= link_to "Delete", users_bounty_path(form.object), data: { turbo_confirm: "Are you sure?", turbo_method: :delete }, class: "no-underline ml-2 rounded-lg py-3 px-5 bg-red-600 text-white inline-block font-medium" %>
      </div>
    <% else %>
      <%= link_to "Cancel", bounties_path, class: "no-underline ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <% end %>
  </div>
<% end %>

app/views/users/bounties/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing bounty</h1>
  <%= render "form", bounty: @bounty %>
</div>

app/views/users/bounties/index.html.erb
<div class="flex justify-between items-center">
  <h2 class="mt-0">My Bounties</h2>
  <%= link_to "New Bounty", new_users_bounty_path, class: "rounded-md bg-indigo-600 py-2 px-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" %>
</div>

<div id="bounties" class="min-w-full">
  <%= render @bounties %>
</div>

<%== pagy_nav(@pagy).html_safe %>

app/views/users/bounties/new.html.erb
<div class="mx-auto">
  <h1 class="font-bold text-4xl">New bounty</h1>

  <div class="bg-white rounded shadow">
    <div class="p-8 bg-gray-100">
      <h3 class="mt-0 text-sm font-medium">Tips for posting bounties</h3>
      <div class="mt-2 text-sm">
        <p>Create a project bounty that is meaningful and manageable for junior developers to complete within a couple of days.</p>
        <p>The bounty should provide a valuable learning opportunity and enable the developer to showcase their skills in a practical setting.</p>
        <p>Please note that we reserve the right to decline any bounties that we feel are unsuitable or unrealistic for our junior developers.</p>
      </div>
    </div>

    <div class="p-8">
      <%= render "form", bounty: @bounty %>
    </div>
  </div>
</div>

app/views/users/bounties/show.html.erb
<div class="mx-auto">
  <%= render @bounty %>
</div>